apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  labels:
   creation_method: manual
   env: prod
   app: demo
spec:
  containers:
  - image: falimonda/kubia-liveness
    name: kubia-liveness
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
     httpGet:
      path: /
      port: 8080
     failureThreshold: 1
     initialDelaySeconds: 20
     periodSeconds: 10
