apiVersion: batch/v1
kind: Job
metadata:
 name: bash-job
spec:
 activeDeadlineSeconds: 300
 backoffLimit: 10
 completions: 1
 parallelism: 1
 template:
  metadata:
   labels:
    app: bash-job
  spec:
   restartPolicy: OnFailure
   containers:
   - name: main
     image: falimonda/sleeper
